# Generated by Django 4.2.1 on 2023-06-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("openApi", "0002_caste_category_commoncoursetype_course_coursetype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenCourseChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(blank=True, max_length=20, null=True)),
                ("choice", models.IntegerField(blank=True, max_length=2)),
                (
                    "stud_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openApi.studmaster",
                    ),
                ),
            ],
        ),
    ]
