# Generated by Django 4.2.1 on 2023-06-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openApi', '0003_opencoursechoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opencoursechoice',
            old_name='stud_details',
            new_name='reg_no',
        ),
        migrations.AddField(
            model_name='opencoursechoice',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opencoursechoice',
            name='choice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
