# Generated by Django 4.2.1 on 2023-07-17 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openApi", "0008_remove_seatsopencourse_botony_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opencoursechoice",
            old_name="reg_no",
            new_name="stud_id",
        ),
        migrations.RemoveField(
            model_name="opencoursechoice",
            name="marks",
        ),
    ]
