# Generated by Django 4.2.1 on 2023-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openApi", "0009_rename_reg_no_opencoursechoice_stud_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opencoursechoice",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
